### ISSUE TITLE
DailyCodingProblem!

### ISSUE THREAD

**Issue by mrpalide** [mahdiZarepoor/AdventOfCodeSolution#1]
Hey Mahdi! What's up?

Check here: https://www.dailycodingproblem.com/

If you was interest call me back. I would like to discuss about problems with one or two others. I'll ask AmirReza too. ;)

Good luck!

**Comment by mahdiZarepoor** [comment]
Hi mohammadreza, how are you doing ? I've almost missed you :)
sure, we can talk about it

**Comment by mrpalide** [comment]
I'm good, I missed you too. :[

Great. I don't know about order of problems, but I get first of it today:

> This problem was recently asked by Google.
Given a list of numbers and a number k, return whether any two numbers from the list add up to k.
For example, given [10, 15, 3, 7] and k of 17, return true since 10 + 7 is 17.

Is it same as yours?

**Comment by mahdiZarepoor** [comment]
YEP, it's t the same as yours
